language: java

addons:
  apt:
    packages:
    - libboost-dev

install: ant -Djam.exec=bjam -DPLATFORM=pc -DLAYOUT=jre

jdk:
- openjdk7

branches:
  only:
  - master

notifications:
  email:
  - chris.gray@kiffer.ltd.uk


