language: C

addons:
  apt:
    packages:
    - gcc-multilib
    - libc6-dev-i386

compiler : gcc

install: (ant -DPLATFORM=pc-awt -DBUILD_TOOL=make && ant -DPLATFORM=pc-awt -DBUILD_TOOL=make tests) || cat build/pc-awt/log/build-pc-awt.log

script: 
  - xvfb-run --server-args="-screen 0 1024x768x24" release/pc-awt/bin/mika -jar release/test/mauve-suite.jar

jdk:
- openjdk7

branches:
  only:
  - master

notifications:
  email:
  - chris.gray@kiffer.ltd.uk


