language: C

addons:
  apt:
    packages:
    - gcc-multilib
    - libc6-dev-i386

compiler : gcc

install: ant -DPLATFORM=pc -DLAYOUT=jre -DBUILD_TOOL=make || cat build/pc/log/build-pc.log

script: release/pc/bin/java -jar release/test/mauve-suite.jar

jdk:
- openjdk7

branches:
  only:
  - master

notifications:
  email:
  - chris.gray@kiffer.ltd.uk


