language: java

addons:
  apt:
    packages:
    - ftjam

install: ant -DPLATFORM=pc -DLAYOUT=jre -DBUILD_TOOL=make

jdk:
- openjdk7

branches:
  only:
  - master

notifications:
  email:
  - chris.gray@kiffer.ltd.uk


