language: C

addons:
  apt:
    packages:
    - gcc-arm-linux-gnueabi
    - libc6-dev-armel-cross
    - qemu-user
    - libffi7_3.3~rc0-7_armel

compiler : gcc

install: ant -DPLATFORM=arm-linux -DBUILD_TOOL=make && ant -DPLATFORM=arm-linux -DBUILD_TOOL=make tests || cat build/arm-linux/log/build-arm-linux.log

script:
  - qemu-arm -L /usr/arm-linux-gnueabi release/arm-linux/bin/mika -jar release/test/mauve-suite.jar

jdk:
- openjdk7

branches:
  only:
  - build.armel

notifications:
  email:
  - chris.gray@kiffer.ltd.uk


